/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiBrokerOrderRouteImport } from './routes/api/broker/order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokerOrderRoute = ApiBrokerOrderRouteImport.update({
  id: '/api/broker/order',
  path: '/api/broker/order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/broker/order': typeof ApiBrokerOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/broker/order': typeof ApiBrokerOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manual': typeof ManualRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/broker/order': typeof ApiBrokerOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manual' | '/api/tape' | '/api/broker/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manual' | '/api/tape' | '/api/broker/order'
  id: '__root__' | '/' | '/manual' | '/api/tape' | '/api/broker/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManualRoute: typeof ManualRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiBrokerOrderRoute: typeof ApiBrokerOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/broker/order': {
      id: '/api/broker/order'
      path: '/api/broker/order'
      fullPath: '/api/broker/order'
      preLoaderRoute: typeof ApiBrokerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManualRoute: ManualRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiBrokerOrderRoute: ApiBrokerOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
